/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5d1e567d0e8b622e6162666b
*
* You will get 10% discount for each one of your friends
* 
*/
import { Component } from '@angular/core';
import { OnInit } from '@angular/core';
// Import Services
import { LoginService } from '../../services/login.service';
// Import Models
import { Login } from '../../domain/evaluacion-docente_db/login';

// START - USED SERVICES
/**
* loginService.delete
*	@description CRUD ACTION delete
*	@param ObjectId id Id
*
* loginService.list
*	@description CRUD ACTION list
*
*/
// END - USED SERVICES

/**
 * This component shows a list of Login
 * @class LoginListComponent
 */
@Component({
    selector: 'app-login-list',
    templateUrl: './login-list.component.html',
    styleUrls: ['./login-list.component.css']
})
export class LoginListComponent implements OnInit {
    list: Login[];
    search: any = {};
    idSelected: string;
    constructor(
        private loginService: LoginService,
    ) { }

    /**
     * Init
     */
    ngOnInit(): void {
        this.loginService.list().subscribe(list => this.list = list);
    }

    /**
     * Select Login to remove
     *
     * @param {string} id Id of the Login to remove
     */
    selectId(id: string) {
        this.idSelected = id;
    }

    /**
     * Remove selected Login
     */
    deleteItem() {
        this.loginService.remove(this.idSelected).subscribe(data => this.list = this.list.filter(el => el._id !== this.idSelected));
    }

}
